name: Update README Stats

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update README.md
        run: |
          sed -i 's|https://github-readme-stats.vercel.app/api?username=AbhijeetSingh1801.*|https://github-readme-stats.vercel.app/api?username=AbhijeetSingh1801\&show_icons=true\&theme=radical\&count_private=true\&token=${{ secrets.GH_STATS_TOKEN }}|' README.md

          sed -i 's|https://github-readme-stats.vercel.app/api/top-langs.*|https://github-readme-stats.vercel.app/api/top-langs/?username=AbhijeetSingh1801\&layout=compact\&theme=radical\&count_private=true\&token=${{ secrets.GH_STATS_TOKEN }}|' README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "chore: update stats with private repos" || echo "No changes"
          git push
