name: Update README Stats

on:
  schedule:
    - cron: "0 */12 * * *" # runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Stats
        run: |
          curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=AbhijeetSingh1801&show_icons=true&theme=radical&count_private=true"
          curl -o langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=AbhijeetSingh1801&layout=compact&theme=radical&count_private=true"

      - name: Commit & Push
        run: |
          git config user.name "Abhijeet Singh"
          git config user.email "abhijeetsingh1801@users.noreply.github.com"
          git add stats.svg langs.svg
          git commit -m "chore: update stats" || echo "No changes to commit"
          git remote set-url origin https://AbhijeetSingh1801:${{ secrets.GH_STATS_TOKEN }}@github.com/AbhijeetSingh1801/AbhijeetSingh1801.git
          git push origin HEAD:master
